- id: cfnguard
  name: cfnguard
  description: "Black: The uncompromising Python code formatter"
  entry: cfnguard
  language: python
  always_run: true
  minimum_pre_commit_version: 2.9.2
  require_serial: false
  types:
    - file
  args:
    - --show-summary
    - --verbose